### ISSUE TITLE
location not loaded in v11

### ISSUE THREAD

**Issue by NicoLouis-be** [bwssytems/nest-controller#4]
version 11
Thermostat: null(075Q), Location: null - nullThermostat: null(075Q), Location: null - null
temperatuur nest: 22

version 8
Thermostat: Living Room(075Q), Location: Living Room - thuis
temperatuur nest: 22

**Comment by bwssytems** [comment]
Yep, just found that and a few others....

**Comment by bwssytems** [comment]
What values do you use out of the devicedetails object?

**Comment by NicoLouis-be** [comment]
non of them, it came with your example 
							if(aWhereItem.getWhereId().equals(thermo.getDeviceDetail().getWhereId())) {
	where = aWhereItem.getName();
	homeName = theNest.getHome(aHomeName).getDetail().getName();
	found = true;
	break;
}

i use thermo.getSharedDetail().getHvacHeaterState() and thermo.getSharedDetail().getTargetTemperature() and send these to my knx ip controller

**Comment by bwssytems** [comment]
Great, I have a fix for it already, it will be up in a moment.

**Comment by NicoLouis-be** [comment]
great work, love this api
made it so easy for me

**Comment by bwssytems** [comment]
It also made my ha-bridge work easier as well. Thanks for the input, helps a lot
