### ISSUE TITLE
settargettemperature

### ISSUE THREAD

**Issue by NicoLouis-be** [bwssytems/nest-controller#5]
hi there

did you try to set the temperature?

i try to use 
		    			Float targetTemp = new Float(theTemp); //theTemp is 20
		    			nestThermostat.getThermo().setTargetTemperature(targetTemp);

but doesn't change the current temperature.

**Comment by bwssytems** [comment]
hmmm, ingeresting, will take a look

**Comment by NicoLouis-be** [comment]
there are some states that don't allow to set the temperature, will try to find out if i'm in one of those but don't think so (reference from the JQuery api - https://github.com/nestlabs/control-jquery/blob/master/app/javascript/nest.js)

  if (thermostat.is_using_emergency_heat) {
    console.error("Can't adjust target temperature while using emergency heat.");
  } else if (thermostat.hvac_mode === 'heat-cool' && !type) {
    console.error("Can't adjust target temperature while in Heat • Cool mode, use target_temperature_high/low instead.");
  } else if (type && thermostat.hvac_mode !== 'heat-cool') {
    console.error("Can't adjust target temperature " + type + " while in " + thermostat.hvac_mode +  " mode, use target_temperature instead.");
  } else if (structure.away.indexOf('away') > -1) {
    console.error("Can't adjust target temperature while structure is set to Away or Auto-away.");
  } else { // ok to set target temperature
    dataRef.child(path).set(newTemp);
  }

**Comment by NicoLouis-be** [comment]
try{
			nestThermostat.getThermo().setTargetTemperature(theTemp);
		} catch (Exception ex){
			System.out.println(ex.getMessage());
		}

gives as result NULL so he goes into the  exception but the exception itself is NULL

**Comment by NicoLouis-be** [comment]
when and from where do you set the URL's ?

more specifique
public void setTransport_url(String transport_url) {
		this.transport_url = transport_url;
	}

to change the temp you call 
	public String getTransport_url() {
		return theAuth.getUrls().getTransport_url();
	}


are they being send from the response after the login?
 theAuth = new Gson().fromJson(authResponse, SessionAuthorization.class);

**Comment by bwssytems** [comment]
You can turn on debugging with the logging framework. Also your examples are your code and not showing how you get the Thermostat logic.

**Comment by NicoLouis-be** [comment]
i'm testing with the testbridge and same result
he runs through the program, URL's are fine, no exception but the temperature just didn't change
